import { Workout } from "../types/hevy";

const workouts: Workout[] = [
  {
    id: "cf2daf8c-53e7-4943-bd15-371232474d6c",
    short_id: "aoc7EjO0BVk",
    index: 4702439,
    name: "Full body",
    description: "",
    start_time: 1657295054,
    end_time: 1657299049,
    weight: 0,
    user_id: "aab17c22-99e4-4302-b168-95e0307a2b6c",
    created_at: "2022-07-08T16:51:01.367Z",
    updated_at: "2022-07-08T16:51:01.367Z",
    routine_id: "972b9c43-5f38-49bd-a5f9-f9f91cce6fef",
    apple_watch: false,
    username: "black2vs2",
    profile_image:
      "https://lh3.googleusercontent.com/a-/AOh14Gg64JYXJ1I5-4ravKDUvRmdimu-yfdutCpOYAV5MQ=s96-c",
    verified: false,
    like_count: 0,
    is_liked_by_user: false,
    like_images: [],
    comments: [],
    comment_count: 0,
    image_urls: [],
    exercises: [
      {
        id: "01072902-0024-4d9b-8357-51674023b93d",
        title: "Chest Press (Machine)",
        es_title: "Press de Pecho (Máquina)",
        de_title: "Brustpresse (Maschine)",
        fr_title: "Chest Press (Machine)",
        it_title: "Chest Press (Macchina)",
        pt_title: "Supino Sentado Máquina",
        superset_id: null,
        rest_seconds: 60,
        notes: "",
        exercise_template_id: "7EB3F7C3",
        url: "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-assets/05771201-Lever-Chest-Press_Chest.mp4",
        exercise_type: "weight_reps",
        equipment_category: "machine",
        media_type: "video",
        custom_exercise_image_url: null,
        custom_exercise_image_thumbnail_url:
          "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-thumbnails/05771201-Lever-Chest-Press_Chest_thumbnail@3x.jpg",
        thumbnail_url:
          "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-thumbnails/05771201-Lever-Chest-Press_Chest_thumbnail@3x.jpg",
        muscle_group: "chest",
        other_muscles: [],
        priority: 9,
        sets: [
          {
            id: 108910282,
            index: 0,
            indicator: "normal",
            weight_kg: 10,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108910283,
            index: 1,
            indicator: "normal",
            weight_kg: 25,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108910284,
            index: 2,
            indicator: "normal",
            weight_kg: 30,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108910285,
            index: 3,
            indicator: "normal",
            weight_kg: 35,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108910286,
            index: 4,
            indicator: "normal",
            weight_kg: 40,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [
              {
                type: "best_weight",
                value: 40,
              },
            ],
          },
        ],
      },
      {
        id: "6962c2a2-0e11-4087-812c-835396263411",
        title: "Seated Cable Row",
        es_title: "Remo Sentado con Cable",
        de_title: "Rudern am Kabel sitzend",
        fr_title: "Rowing Poulie Assis",
        it_title: "Rematore al Cavo da Seduto",
        pt_title: "Remada (Corda) Sentado",
        superset_id: null,
        rest_seconds: 60,
        notes: "",
        exercise_template_id: "F1D60854",
        url: "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-assets/01801201-Cable-Low-Seated-Row_Back.mp4",
        exercise_type: "weight_reps",
        equipment_category: "machine",
        media_type: "video",
        custom_exercise_image_url: null,
        custom_exercise_image_thumbnail_url:
          "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-thumbnails/01801201-Cable-Low-Seated-Row_Back_thumbnail@3x.jpg",
        thumbnail_url:
          "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-thumbnails/01801201-Cable-Low-Seated-Row_Back_thumbnail@3x.jpg",
        muscle_group: "upper_back",
        other_muscles: [],
        priority: 10,
        sets: [
          {
            id: 108910287,
            index: 0,
            indicator: "normal",
            weight_kg: 15,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108910288,
            index: 1,
            indicator: "normal",
            weight_kg: 25,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108910289,
            index: 2,
            indicator: "normal",
            weight_kg: 30,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108910290,
            index: 3,
            indicator: "normal",
            weight_kg: 35,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [
              {
                type: "best_weight",
                value: 35,
              },
            ],
          },
        ],
      },
      {
        id: "d4b80f2c-521a-4ccb-8f0e-0612fe11a207",
        title: "Seated Shoulder Press (Machine)",
        es_title: "Press de Hombros Sentado (Máquina)",
        de_title: "Schulterpresse sitzend (Maschine)",
        fr_title: "Presse Épaules Assis (Machine)",
        it_title: "Lento in Avanti Seduto (Macchina)",
        pt_title: "Pensa De Ombros (Sentada) (Máquina)",
        superset_id: null,
        rest_seconds: 60,
        notes: "",
        exercise_template_id: "9237BAD1",
        url: "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-assets/14541201-Lever-Seated-Shoulder-Press_Shoulders.mp4",
        exercise_type: "weight_reps",
        equipment_category: "machine",
        media_type: "video",
        custom_exercise_image_url: null,
        custom_exercise_image_thumbnail_url:
          "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-thumbnails/14541201-Lever-Seated-Shoulder-Press_Shoulders_thumbnail@3x.jpg",
        thumbnail_url:
          "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-thumbnails/14541201-Lever-Seated-Shoulder-Press_Shoulders_thumbnail@3x.jpg",
        muscle_group: "shoulders",
        other_muscles: ["triceps"],
        priority: 0,
        sets: [
          {
            id: 108910291,
            index: 0,
            indicator: "normal",
            weight_kg: 20,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108910292,
            index: 1,
            indicator: "normal",
            weight_kg: 25,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108910293,
            index: 2,
            indicator: "normal",
            weight_kg: 30,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108910294,
            index: 3,
            indicator: "normal",
            weight_kg: 35,
            reps: 6,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
        ],
      },
      {
        id: "6b705a83-df3a-452e-b465-b16b824ca79c",
        title: "Lat Pulldown (Cable)",
        es_title: "Jalón al Pecho (Cable)",
        de_title: "Latzug (Kabel)",
        fr_title: "Tirage Poitrine (Poulie)",
        it_title: "Lat Pulldown (Cavo)",
        pt_title: "Puxadas (Corda)",
        superset_id: null,
        rest_seconds: 60,
        notes: "",
        exercise_template_id: "6A6C31A5",
        url: "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-assets/01501201-Cable-Bar-Lateral-Pulldown_Back.mp4",
        exercise_type: "weight_reps",
        equipment_category: "machine",
        media_type: "video",
        custom_exercise_image_url: null,
        custom_exercise_image_thumbnail_url:
          "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-thumbnails/01501201-Cable-Bar-Lateral-Pulldown_Back_thumbnail@3x.jpg",
        thumbnail_url:
          "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-thumbnails/01501201-Cable-Bar-Lateral-Pulldown_Back_thumbnail@3x.jpg",
        muscle_group: "lats",
        other_muscles: [],
        priority: 10,
        sets: [
          {
            id: 108910295,
            index: 0,
            indicator: "normal",
            weight_kg: 20,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108910296,
            index: 1,
            indicator: "normal",
            weight_kg: 25,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108910297,
            index: 2,
            indicator: "normal",
            weight_kg: 30,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108910298,
            index: 3,
            indicator: "normal",
            weight_kg: 35,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108910299,
            index: 4,
            indicator: "normal",
            weight_kg: 40,
            reps: 8,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
        ],
      },
      {
        id: "7bbf4d85-4644-403e-8be4-6ac9af589f0c",
        title: "Hammer Curl (Dumbbell)",
        es_title: "Curl Martillo (Mancuerna)",
        de_title: "Hammer Curl (Kurzhantel)",
        fr_title: "Curl Marteau (Haltère)",
        it_title: "Bicipiti Martello (Manubrio)",
        pt_title: "Curl Em Martelo (Haltere)",
        superset_id: null,
        rest_seconds: 60,
        notes: "",
        exercise_template_id: "7E3BC8B6",
        url: "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-assets/03121201-Dumbbell-Hammer-Curl-(version-2)_Upper-Arms.mp4",
        exercise_type: "weight_reps",
        equipment_category: "dumbbell",
        media_type: "video",
        custom_exercise_image_url: null,
        custom_exercise_image_thumbnail_url:
          "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-thumbnails/03121201-Dumbbell-Hammer-Curl-(version-2)_Upper-Arms_thumbnail@3x.jpg",
        thumbnail_url:
          "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-thumbnails/03121201-Dumbbell-Hammer-Curl-(version-2)_Upper-Arms_thumbnail@3x.jpg",
        muscle_group: "biceps",
        other_muscles: [],
        priority: 10,
        sets: [
          {
            id: 108910300,
            index: 0,
            indicator: "normal",
            weight_kg: 4,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108910301,
            index: 1,
            indicator: "normal",
            weight_kg: 4,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108910302,
            index: 2,
            indicator: "normal",
            weight_kg: 4,
            reps: 11,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108910303,
            index: 3,
            indicator: "normal",
            weight_kg: 4,
            reps: 10,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
        ],
      },
      {
        id: "57b13125-9ac6-4c1e-83ce-6cf2aab2120a",
        title: "Triceps Rope Pushdown",
        es_title: null,
        de_title: "Trizepsdrücken mit dem Seil",
        fr_title: "Extension Triceps Corde",
        it_title: "Pushdown Tricipiti con Corda",
        pt_title: "Puxada De Triceps (Corda)",
        superset_id: null,
        rest_seconds: 60,
        notes: "",
        exercise_template_id: "94B7239B",
        url: "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-assets/02001101-Cable-Pushdown-(with-rope-attachment)_Upper-Arms_small.jpg",
        exercise_type: "weight_reps",
        equipment_category: "machine",
        media_type: "image",
        custom_exercise_image_url: null,
        custom_exercise_image_thumbnail_url:
          "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-thumbnails/02001101-Cable-Pushdown-(with-rope-attachment)_Upper-Arms_small_thumbnail@3x.jpg",
        thumbnail_url:
          "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-thumbnails/02001101-Cable-Pushdown-(with-rope-attachment)_Upper-Arms_small_thumbnail@3x.jpg",
        muscle_group: "triceps",
        other_muscles: [],
        priority: 10,
        sets: [
          {
            id: 108910304,
            index: 0,
            indicator: "normal",
            weight_kg: 7.5,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108910305,
            index: 1,
            indicator: "normal",
            weight_kg: 10,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108910306,
            index: 2,
            indicator: "normal",
            weight_kg: 12.5,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108910307,
            index: 3,
            indicator: "normal",
            weight_kg: 12.5,
            reps: 10,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108910308,
            index: 4,
            indicator: "normal",
            weight_kg: 12.5,
            reps: 7,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
        ],
      },
      {
        id: "5d57a2ee-a9e7-41ec-b2f8-f8ee78786c2e",
        title: "Leg Press Horizontal (Machine)",
        es_title: "Press de Piernas Sentado",
        de_title: "Beinpresse sitzend",
        fr_title: "Presse à Cuisses Horizontal",
        it_title: "Leg Press Orizzontale (Macchina)",
        pt_title: "Press De Pernas Horizontal (Máquina)",
        superset_id: null,
        rest_seconds: 60,
        notes: "",
        exercise_template_id: "0EB695C9",
        url: "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-assets/22671201-Lever-Seated-Leg-Press_Thighs.mp4",
        exercise_type: "weight_reps",
        equipment_category: "machine",
        media_type: "video",
        custom_exercise_image_url: null,
        custom_exercise_image_thumbnail_url:
          "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-thumbnails/22671201-Lever-Seated-Leg-Press_Thighs_thumbnail@3x.jpg",
        thumbnail_url:
          "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-thumbnails/22671201-Lever-Seated-Leg-Press_Thighs_thumbnail@3x.jpg",
        muscle_group: "quadriceps",
        other_muscles: ["hamstrings", "glutes"],
        priority: 10,
        sets: [
          {
            id: 108910309,
            index: 0,
            indicator: "normal",
            weight_kg: 60,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108910310,
            index: 1,
            indicator: "normal",
            weight_kg: 70,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108910311,
            index: 2,
            indicator: "normal",
            weight_kg: 90,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108910312,
            index: 3,
            indicator: "normal",
            weight_kg: 100,
            reps: 10,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
        ],
      },
      {
        id: "eea4ffe4-ba2b-485c-8d3e-d8a879a001d0",
        title: "Leg Extension (Machine)",
        es_title: "Extensión de Pierna",
        de_title: "Beinstrecken ",
        fr_title: "Extension Jambes",
        it_title: "Leg Extension (Macchina)",
        pt_title: "Extensão De Perna (Máquina)",
        superset_id: null,
        rest_seconds: 60,
        notes: "",
        exercise_template_id: "75A4F6C4",
        url: "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-assets/05851201-Lever-Leg-Extension_Thighs.mp4",
        exercise_type: "weight_reps",
        equipment_category: "machine",
        media_type: "video",
        custom_exercise_image_url: null,
        custom_exercise_image_thumbnail_url:
          "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-thumbnails/05851201-Lever-Leg-Extension_Thighs_thumbnail@3x.jpg",
        thumbnail_url:
          "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-thumbnails/05851201-Lever-Leg-Extension_Thighs_thumbnail@3x.jpg",
        muscle_group: "quadriceps",
        other_muscles: [],
        priority: 10,
        sets: [
          {
            id: 108910313,
            index: 0,
            indicator: "normal",
            weight_kg: 25,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108910314,
            index: 1,
            indicator: "normal",
            weight_kg: 30,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108910315,
            index: 2,
            indicator: "normal",
            weight_kg: 35,
            reps: 10,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108910316,
            index: 3,
            indicator: "normal",
            weight_kg: 35,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
        ],
      },
    ],
  },
  {
    id: "20e0baf4-fa67-4faa-8726-1dda0c7d417f",
    short_id: "11EZfrwPUUT",
    index: 4657538,
    name: "Full body",
    description: "",
    start_time: 1657110031,
    end_time: 1657117231,
    weight: 0,
    user_id: "aab17c22-99e4-4302-b168-95e0307a2b6c",
    created_at: "2022-07-06T12:44:52.018Z",
    updated_at: "2022-07-06T17:32:26.503Z",
    routine_id: "972b9c43-5f38-49bd-a5f9-f9f91cce6fef",
    apple_watch: false,
    username: "black2vs2",
    profile_image:
      "https://lh3.googleusercontent.com/a-/AOh14Gg64JYXJ1I5-4ravKDUvRmdimu-yfdutCpOYAV5MQ=s96-c",
    verified: false,
    like_count: 0,
    is_liked_by_user: false,
    like_images: [],
    comments: [],
    comment_count: 0,
    image_urls: [],
    exercises: [
      {
        id: "afc1aa14-c3a4-4b12-b0ce-9ef97e18c559",
        title: "Chest Press (Machine)",
        es_title: "Press de Pecho (Máquina)",
        de_title: "Brustpresse (Maschine)",
        fr_title: "Chest Press (Machine)",
        it_title: "Chest Press (Macchina)",
        pt_title: "Supino Sentado Máquina",
        superset_id: null,
        rest_seconds: 60,
        notes: "",
        exercise_template_id: "7EB3F7C3",
        url: "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-assets/05771201-Lever-Chest-Press_Chest.mp4",
        exercise_type: "weight_reps",
        equipment_category: "machine",
        media_type: "video",
        custom_exercise_image_url: null,
        custom_exercise_image_thumbnail_url:
          "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-thumbnails/05771201-Lever-Chest-Press_Chest_thumbnail@3x.jpg",
        thumbnail_url:
          "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-thumbnails/05771201-Lever-Chest-Press_Chest_thumbnail@3x.jpg",
        muscle_group: "chest",
        other_muscles: [],
        priority: 9,
        sets: [
          {
            id: 108010924,
            index: 0,
            indicator: "normal",
            weight_kg: 10,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108010925,
            index: 1,
            indicator: "normal",
            weight_kg: 15,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108010926,
            index: 2,
            indicator: "normal",
            weight_kg: 20,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [
              {
                type: "best_weight",
                value: 20,
              },
            ],
          },
          {
            id: 108010927,
            index: 3,
            indicator: "normal",
            weight_kg: 20,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108010928,
            index: 4,
            indicator: "normal",
            weight_kg: 20,
            reps: 12,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
        ],
      },
      {
        id: "afdd1729-d438-4bf5-9822-053484216df3",
        title: "Seated Cable Row - Wide Grip",
        es_title: "Remo Sentado con Cable - Agarre Abierto",
        de_title: "Sitzendes Rudern - Weiter Griff",
        fr_title: "Rowing Poulie Assis - Prise Large",
        it_title: "Rematore al Cavo da Seduto - Presa Larga",
        pt_title: "Remada (Corda) Sentado - Pegas Afastadas",
        superset_id: null,
        rest_seconds: 60,
        notes: "",
        exercise_template_id: "C3BCABB3",
        url: "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-assets/02181201-Cable-Seated-Wide-grip-Row_Back.mp4",
        exercise_type: "weight_reps",
        equipment_category: "machine",
        media_type: "video",
        custom_exercise_image_url: null,
        custom_exercise_image_thumbnail_url:
          "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-thumbnails/02181201-Cable-Seated-Wide-grip-Row_Back_thumbnail@3x.jpg",
        thumbnail_url:
          "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-thumbnails/02181201-Cable-Seated-Wide-grip-Row_Back_thumbnail@3x.jpg",
        muscle_group: "upper_back",
        other_muscles: [],
        priority: 0,
        sets: [
          {
            id: 108010929,
            index: 0,
            indicator: "normal",
            weight_kg: 15,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108010930,
            index: 1,
            indicator: "normal",
            weight_kg: 20,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108010931,
            index: 2,
            indicator: "normal",
            weight_kg: 25,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [
              {
                type: "best_weight",
                value: 25,
              },
            ],
          },
          {
            id: 108010932,
            index: 3,
            indicator: "normal",
            weight_kg: 25,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
        ],
      },
      {
        id: "f7ba984e-7c06-4fb0-bdf1-970e07e1f2db",
        title: "Iso-Lateral Row (Machine)",
        es_title: "Remo Iso-Lateral",
        de_title: "Iso-Laterales Rudern",
        fr_title: "Tirage Machine Convergente",
        it_title: "Rematore Convergente (Macchina)",
        pt_title: "Remadas Iso-Lateral (Máquina)",
        superset_id: null,
        rest_seconds: 0,
        notes: "",
        exercise_template_id: "AA1EB7D8",
        url: "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-assets/05881101-Lever-Narrow-Grip-Seated-Row-(plate-loaded)_Back_small.jpg",
        exercise_type: "weight_reps",
        equipment_category: "machine",
        media_type: "image",
        custom_exercise_image_url: null,
        custom_exercise_image_thumbnail_url:
          "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-thumbnails/05881101-Lever-Narrow-Grip-Seated-Row-(plate-loaded)_Back_small_thumbnail@3x.jpg",
        thumbnail_url:
          "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-thumbnails/05881101-Lever-Narrow-Grip-Seated-Row-(plate-loaded)_Back_small_thumbnail@3x.jpg",
        muscle_group: "lats",
        other_muscles: [],
        priority: 0,
        sets: [
          {
            id: 108010933,
            index: 0,
            indicator: "normal",
            weight_kg: 15,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108010934,
            index: 1,
            indicator: "normal",
            weight_kg: 20,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108010935,
            index: 2,
            indicator: "normal",
            weight_kg: 25,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [
              {
                type: "best_weight",
                value: 25,
              },
            ],
          },
          {
            id: 108010936,
            index: 3,
            indicator: "normal",
            weight_kg: 25,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
        ],
      },
      {
        id: "ae328151-782a-4c6d-bee3-dbff02d117e3",
        title: "Seated Shoulder Press (Machine)",
        es_title: "Press de Hombros Sentado (Máquina)",
        de_title: "Schulterpresse sitzend (Maschine)",
        fr_title: "Presse Épaules Assis (Machine)",
        it_title: "Lento in Avanti Seduto (Macchina)",
        pt_title: "Pensa De Ombros (Sentada) (Máquina)",
        superset_id: null,
        rest_seconds: 60,
        notes: "",
        exercise_template_id: "9237BAD1",
        url: "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-assets/14541201-Lever-Seated-Shoulder-Press_Shoulders.mp4",
        exercise_type: "weight_reps",
        equipment_category: "machine",
        media_type: "video",
        custom_exercise_image_url: null,
        custom_exercise_image_thumbnail_url:
          "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-thumbnails/14541201-Lever-Seated-Shoulder-Press_Shoulders_thumbnail@3x.jpg",
        thumbnail_url:
          "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-thumbnails/14541201-Lever-Seated-Shoulder-Press_Shoulders_thumbnail@3x.jpg",
        muscle_group: "shoulders",
        other_muscles: ["triceps"],
        priority: 0,
        sets: [
          {
            id: 108010937,
            index: 0,
            indicator: "normal",
            weight_kg: 20,
            reps: 10,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108010938,
            index: 1,
            indicator: "normal",
            weight_kg: 25,
            reps: 10,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108010939,
            index: 2,
            indicator: "normal",
            weight_kg: 30,
            reps: 10,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108010940,
            index: 3,
            indicator: "normal",
            weight_kg: 35,
            reps: 10,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [
              {
                type: "best_weight",
                value: 35,
              },
            ],
          },
        ],
      },
      {
        id: "bf722d02-f511-4451-92a7-4beca037e5cf",
        title: "Lat Pulldown (Cable)",
        es_title: "Jalón al Pecho (Cable)",
        de_title: "Latzug (Kabel)",
        fr_title: "Tirage Poitrine (Poulie)",
        it_title: "Lat Pulldown (Cavo)",
        pt_title: "Puxadas (Corda)",
        superset_id: null,
        rest_seconds: 60,
        notes: "",
        exercise_template_id: "6A6C31A5",
        url: "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-assets/01501201-Cable-Bar-Lateral-Pulldown_Back.mp4",
        exercise_type: "weight_reps",
        equipment_category: "machine",
        media_type: "video",
        custom_exercise_image_url: null,
        custom_exercise_image_thumbnail_url:
          "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-thumbnails/01501201-Cable-Bar-Lateral-Pulldown_Back_thumbnail@3x.jpg",
        thumbnail_url:
          "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-thumbnails/01501201-Cable-Bar-Lateral-Pulldown_Back_thumbnail@3x.jpg",
        muscle_group: "lats",
        other_muscles: [],
        priority: 10,
        sets: [
          {
            id: 108010941,
            index: 0,
            indicator: "normal",
            weight_kg: 20,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108010942,
            index: 1,
            indicator: "normal",
            weight_kg: 25,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108010943,
            index: 2,
            indicator: "normal",
            weight_kg: 30,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108010944,
            index: 3,
            indicator: "normal",
            weight_kg: 35,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108010945,
            index: 4,
            indicator: "normal",
            weight_kg: 40,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [
              {
                type: "best_weight",
                value: 40,
              },
            ],
          },
        ],
      },
      {
        id: "ba235b57-d002-46eb-9e2b-280f1874e83f",
        title: "Hammer Curl (Dumbbell)",
        es_title: "Curl Martillo (Mancuerna)",
        de_title: "Hammer Curl (Kurzhantel)",
        fr_title: "Curl Marteau (Haltère)",
        it_title: "Bicipiti Martello (Manubrio)",
        pt_title: "Curl Em Martelo (Haltere)",
        superset_id: null,
        rest_seconds: 60,
        notes: "",
        exercise_template_id: "7E3BC8B6",
        url: "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-assets/03121201-Dumbbell-Hammer-Curl-(version-2)_Upper-Arms.mp4",
        exercise_type: "weight_reps",
        equipment_category: "dumbbell",
        media_type: "video",
        custom_exercise_image_url: null,
        custom_exercise_image_thumbnail_url:
          "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-thumbnails/03121201-Dumbbell-Hammer-Curl-(version-2)_Upper-Arms_thumbnail@3x.jpg",
        thumbnail_url:
          "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-thumbnails/03121201-Dumbbell-Hammer-Curl-(version-2)_Upper-Arms_thumbnail@3x.jpg",
        muscle_group: "biceps",
        other_muscles: [],
        priority: 10,
        sets: [
          {
            id: 108010946,
            index: 0,
            indicator: "normal",
            weight_kg: 4,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108010947,
            index: 1,
            indicator: "normal",
            weight_kg: 4,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108010948,
            index: 2,
            indicator: "normal",
            weight_kg: 6,
            reps: 8,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [
              {
                type: "best_weight",
                value: 6,
              },
            ],
          },
          {
            id: 108010949,
            index: 3,
            indicator: "normal",
            weight_kg: 4,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
        ],
      },
      {
        id: "611c5d2f-2f6e-4df9-a479-a7a97d8647b7",
        title: "Triceps Rope Pushdown",
        es_title: null,
        de_title: "Trizepsdrücken mit dem Seil",
        fr_title: "Extension Triceps Corde",
        it_title: "Pushdown Tricipiti con Corda",
        pt_title: "Puxada De Triceps (Corda)",
        superset_id: null,
        rest_seconds: 60,
        notes: "",
        exercise_template_id: "94B7239B",
        url: "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-assets/02001101-Cable-Pushdown-(with-rope-attachment)_Upper-Arms_small.jpg",
        exercise_type: "weight_reps",
        equipment_category: "machine",
        media_type: "image",
        custom_exercise_image_url: null,
        custom_exercise_image_thumbnail_url:
          "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-thumbnails/02001101-Cable-Pushdown-(with-rope-attachment)_Upper-Arms_small_thumbnail@3x.jpg",
        thumbnail_url:
          "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-thumbnails/02001101-Cable-Pushdown-(with-rope-attachment)_Upper-Arms_small_thumbnail@3x.jpg",
        muscle_group: "triceps",
        other_muscles: [],
        priority: 10,
        sets: [
          {
            id: 108010950,
            index: 0,
            indicator: "normal",
            weight_kg: 7.5,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108010951,
            index: 1,
            indicator: "normal",
            weight_kg: 10,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108010952,
            index: 2,
            indicator: "normal",
            weight_kg: 12.5,
            reps: 10,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [
              {
                type: "best_weight",
                value: 12.5,
              },
            ],
          },
          {
            id: 108010953,
            index: 3,
            indicator: "normal",
            weight_kg: 12.5,
            reps: 10,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108010954,
            index: 4,
            indicator: "normal",
            weight_kg: 12.5,
            reps: 10,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
        ],
      },
      {
        id: "aa80109f-7bf4-43a1-b975-5948e0cd1f5c",
        title: "Leg Press Horizontal (Machine)",
        es_title: "Press de Piernas Sentado",
        de_title: "Beinpresse sitzend",
        fr_title: "Presse à Cuisses Horizontal",
        it_title: "Leg Press Orizzontale (Macchina)",
        pt_title: "Press De Pernas Horizontal (Máquina)",
        superset_id: null,
        rest_seconds: 60,
        notes: "",
        exercise_template_id: "0EB695C9",
        url: "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-assets/22671201-Lever-Seated-Leg-Press_Thighs.mp4",
        exercise_type: "weight_reps",
        equipment_category: "machine",
        media_type: "video",
        custom_exercise_image_url: null,
        custom_exercise_image_thumbnail_url:
          "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-thumbnails/22671201-Lever-Seated-Leg-Press_Thighs_thumbnail@3x.jpg",
        thumbnail_url:
          "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-thumbnails/22671201-Lever-Seated-Leg-Press_Thighs_thumbnail@3x.jpg",
        muscle_group: "quadriceps",
        other_muscles: ["hamstrings", "glutes"],
        priority: 10,
        sets: [
          {
            id: 108010955,
            index: 0,
            indicator: "normal",
            weight_kg: 60,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108010956,
            index: 1,
            indicator: "normal",
            weight_kg: 70,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108010957,
            index: 2,
            indicator: "normal",
            weight_kg: 90,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108010958,
            index: 3,
            indicator: "normal",
            weight_kg: 100,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [
              {
                type: "best_weight",
                value: 100,
              },
            ],
          },
        ],
      },
      {
        id: "4a625363-7c92-4196-93b4-27ee81d6db9b",
        title: "Leg Extension (Machine)",
        es_title: "Extensión de Pierna",
        de_title: "Beinstrecken ",
        fr_title: "Extension Jambes",
        it_title: "Leg Extension (Macchina)",
        pt_title: "Extensão De Perna (Máquina)",
        superset_id: null,
        rest_seconds: 60,
        notes: "",
        exercise_template_id: "75A4F6C4",
        url: "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-assets/05851201-Lever-Leg-Extension_Thighs.mp4",
        exercise_type: "weight_reps",
        equipment_category: "machine",
        media_type: "video",
        custom_exercise_image_url: null,
        custom_exercise_image_thumbnail_url:
          "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-thumbnails/05851201-Lever-Leg-Extension_Thighs_thumbnail@3x.jpg",
        thumbnail_url:
          "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-thumbnails/05851201-Lever-Leg-Extension_Thighs_thumbnail@3x.jpg",
        muscle_group: "quadriceps",
        other_muscles: [],
        priority: 10,
        sets: [
          {
            id: 108010959,
            index: 0,
            indicator: "normal",
            weight_kg: 25,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108010960,
            index: 1,
            indicator: "normal",
            weight_kg: 30,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108010961,
            index: 2,
            indicator: "normal",
            weight_kg: 35,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [
              {
                type: "best_weight",
                value: 35,
              },
            ],
          },
          {
            id: 108010962,
            index: 3,
            indicator: "normal",
            weight_kg: 35,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
        ],
      },
      {
        id: "18fcb651-ea92-49fe-9474-96f6025444af",
        title: "Seated Leg Curl (Machine)",
        es_title: "Curl de Pierna Sentado",
        de_title: "Beinbeugen sitzend",
        fr_title: "Leg Curl Assis",
        it_title: "Leg Curl Seduto (Macchina)",
        pt_title: "Curl De Pernas (Sentado) (Máquina)",
        superset_id: null,
        rest_seconds: 60,
        notes: "",
        exercise_template_id: "11A123F3",
        url: "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-assets/05991201-Lever-Seated-Leg-Curl_Thighs.mp4",
        exercise_type: "weight_reps",
        equipment_category: "machine",
        media_type: "video",
        custom_exercise_image_url: null,
        custom_exercise_image_thumbnail_url:
          "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-thumbnails/05991201-Lever-Seated-Leg-Curl_Thighs_thumbnail@3x.jpg",
        thumbnail_url:
          "https://pump-app.s3.eu-west-2.amazonaws.com/exercise-thumbnails/05991201-Lever-Seated-Leg-Curl_Thighs_thumbnail@3x.jpg",
        muscle_group: "hamstrings",
        other_muscles: [],
        priority: 0,
        sets: [
          {
            id: 108010963,
            index: 0,
            indicator: "normal",
            weight_kg: 20,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108010964,
            index: 1,
            indicator: "normal",
            weight_kg: 25,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [],
          },
          {
            id: 108010965,
            index: 2,
            indicator: "normal",
            weight_kg: 30,
            reps: 15,
            distance_meters: null,
            duration_seconds: null,
            rpe: null,
            personalRecords: [
              {
                type: "best_weight",
                value: 30,
              },
            ],
          },
        ],
      },
    ],
  },
];

export default { workouts };
